routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

  Route::prefix('admin')->group(function () {

    Route::get('testing','adminController@test');
    Route::get('/seo','adminController@seoIndex')->name('seoIndex');
    Route::get('/seoCreate','adminController@seoCreate')->name('seoCreate');
    Route::post('/seoStore','adminController@seoStore')->name('seoStore');
    Route::get('/seoEdit/{id}','adminController@seoEdit')->name('seoEdit');
    Route::post('/seoPut','adminController@seoPut')->name('seoPut');
    Route::get('/seoCollection','adminController@seoCollection')->name('seoCollection');
    Route::get('/','adminController@home')->name('adminHome');
    Route::post('/checkStatus','adminController@checkStatus')->name('checkStatus');
    Route::get('/subscriberData','adminController@subscriberData')->name('subscriberData');
    Route::get('/subscribLetterList','adminController@subscribLetterList')->name('subscribLetterList');
    Route::get('/userMessages','adminController@userMessages')->name('userMessages');
    Route::get('/getUserMessageJson','adminController@getUserMessageJson')->name('getUserMessageJson');
    Route::post('/setUserMessageSeen','adminController@setUserMessageSeen')->name('setUserMessageSeen');
    Route::post('/deleteUserMessage','adminController@deleteUserMessage')->name('deleteUserMessage');
    Route::post('/deleteDestination','adminController@deleteDestination')->name('deleteDestination');
    Route::get('/destination','adminController@destination')->name('adminDestination');
    Route::get('/createDestination','adminController@createDestination')->name('createDestination');
    Route::post('/addDestination','adminController@addDestination')->name('addDestination');
    Route::get('/editDestination/{id}','adminController@editDestination')->name('editDestination');
    Route::post('/updateDestination/{id}','adminController@updateDestination')->name('updateDestination');
    Route::get('/vehicles','adminController@vehicles')->name('adminVehicles');
    Route::get('/createVehicle','adminController@createVehicle')->name('createVehicle');
    Route::post('/addVehicle','adminController@addVehicle')->name('addVehicle');
    Route::get('/editVehicle/{id}','adminController@editVehicle')->name('editVehicle');
    Route::post('/updateVehicle/{id}','adminController@updateVehicle')->name('updateVehicle');
    Route::post('/deleteVehicle','adminController@deleteVehicle')->name('deleteVehicle');
    Route::post('/deleteSubsriber','adminController@deleteSubsriber')->name('deleteSubsriber');
    Route::post('/deleteGalleryImage','adminController@deleteGalleryImage')->name('deleteGalleryImage');
    Route::get('/vehicleBooking','adminController@vehicleBooking')->name('vehicleBooking');
    Route::post('/getVehicleBooking','adminController@getVehicleBooking')->name('getVehicleBooking');
    Route::post('/deleteBooking','adminController@deleteBooking')->name('deleteBooking');
    Route::post('setBookingSeen','adminController@setBookingSeen')->name('setBookingSeen');
    Route::get('/pickDrop','adminController@pickDrop')->name('pickDropAdmin');
    Route::post('/getPickDrop','adminController@getPickDrop')->name('getPickDrop');
    Route::post('/deletePickAndDrop','adminController@deletePickAndDrop')->name('deletePickAndDrop');
    Route::post('/setPickAndDrop','adminController@setPickAndDrop')->name('setPickAndDrop');
    Route::post('/getInitilizationData','adminController@getInitilizationData')->name('getInitilizationData');
    Route::post('/deleteDestinationGalleryImage','adminController@deleteDestinationGalleryImage')->name('deleteDestinationGalleryImage');
});

Auth::routes();

Route::post('getVehcilesJson','VehicleController@getVehcilesJson')->name('getVehcilesJson');
Route::resource('pickAndDrop','PickAndDropController');
Route::get('/', 'HomeController@index')->name('ahome');
Route::get('/', 'HomeController@index')->name('home');
Route::get('/home',function(){
  return Redirect::to('/');
});
Route::post('/subscribNewLetter','NewsLetterController@store')->name('subscribNewLetter');
Route::post('/userMessageSave','UserMessageController@store')->name('userMessageSave');
Route::get('vehicle/{id}/{name?}','VehicleController@vehicle');
Route::resource('/rental-vehicles','VehicleController');
Route::resource('/services','ServiceController');
Route::get('/rent-a-car','ServiceController@rentACar')->name('rent-a-Car');
Route::get('/tour-management','ServiceController@tourManagement')->name('tour-management');
Route::get('/pick-and-drop','ServiceController@pickAndDrop')->name('pick-and-drop');
Route::get('/policy',function(){
  return view('policy');
})->name('policy');
Route::get('/tourist-attraction','DestinationController@provinces')->name('provinces');
Route::post('/car-Booking',"carBookingController@store")->name('car-Booking');
Route::get('/tourist-attraction-Detail/{id}/{title?}','DestinationController@destination')->name('destination');
Route::get('/tourist-attraction/{id}/{title?}','DestinationController@provinceNew')->name('provinceNew');
Route::resource('/destinations','DestinationController');
Route::post('planTour','TourController@planeTour')->name('planeTour');
Route::resource('/plan-my-tour','TourController');
Route::get('contact-us','UserMessageController@index')->name('contact-us');
Route::get('/loyalty-card',function(){
  return view('loyalty-card');
})->name('loyalty-card');

app/service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class service extends Model
{
    //
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;

use App\service;
use Illuminate\Http\Request;

class ServiceController extends Controller
{
    public function rentACar(){
      return view('service.rentACar');
    }
    public function tourManagement(){
      return view('service.tourManagement');
    }
    public function pickAndDrop(){
      return view('service.pickAndDrop');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('service.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\service  $service
     * @return \Illuminate\Http\Response
     */
    public function show(service $service)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\service  $service
     * @return \Illuminate\Http\Response
     */
    public function edit(service $service)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\service  $service
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, service $service)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\service  $service
     * @return \Illuminate\Http\Response
     */
    public function destroy(service $service)
    {
        //
    }
}

resources/views/service/index.blade.php
@extends('layouts.app')
@section('title','Rent a Car | Economy Car Rental Deals | Car for Rent')
@section('body')

  <div class="full-r"><img src="{{asset("img/service-banner.jpg")}}"  alt="Rental Car Services - Pick and Drop Services - Bhai Sahab transport" title="Rental Car Services - Pick and Drop Services - Bhai Sahab transport"/></div>
  <div class="container" itemscope itemtype="http://schema.org/ProfessionalService">
  	<div class="row" itemprop="description">
  		<div class="col-md-12">
              <div class="col-sm-8 col-md-8 col-lg-9" style="text-align: justify;line-height:27px;padding: 0px 20px 15px;font-size:17px;font-family:'Roboto', arial, helvetica, sans-serif;">
                  <h1 style="margin-top:20px;">Lahore Rent a Car Service </h1>
                  <p>Bhai Sahab Transport is well-recognized transport company across Lahore. We deliver innovative Lahore Rent a Car service at most affordable packages that can afford by every user. Our mission is to serve citizens with our convenient travel services anywhere in Lahore. With our comfortable cars and most caring staff, you can enjoy your every tour and make it memorable. We have well-trained drivers and most efficient cars to save your precious time during travel. With our huge experience, we can meet all your travel requirements with our top quality Lahore rent a car service. So, if you are planning for long term or short term tour, stop looking anywhere else because Bhai Sahab Transport is reasonable choice for you. Let’s consult our team to hire the best car on rent.</p>
              </div>

              <div class="col-sm-4 col-md-4 col-lg-3">
              <div class="row">
                  <h5 class="" style="margin-top: 20px; border-bottom: 2px solid rgb(237, 131, 35); padding-bottom: 5px;">Contact Us for pick and drop service with in Lahore.</h5>
                  <aside class="sidebar-left">
                    <form id="service-contact">
                        <div class="form-group form-group-icon-left">
                            <input maxlength="150" class="form-control form-control-2" value="" id="name" placeholder="Name" type="text">
                            <span class="spanError form-control-2" id="spanContactName"></span>
                        </div>
                        <div class="form-group form-group-icon-left">
                            <input class="form-control form-control-2" id="phoneNo" placeholder="Phone No" type="text">
                            <span class="spanError form-control-2" id="spanContactPhone"></span>
                        </div>
                        <div class="form-group form-group-icon-left">
                            <input class="form-control form-control-2" id="institute" placeholder="College / University" type="text">
                            <span class="spanError form-control-2" id="spanContactLocation"></span>
                        </div>
                        <div class="form-group form-group-icon-left">
                            <select id="vehicle_type" class="form-control form-control-2">
                                <option disabled selected value="no">Vehicle Type</option>
                                <option value="Rickshaw">Rickshaw</option>
                                <option value="Other">Others</option>
                            </select>
                            <span class="spanError form-control-2" id="spanVehicleType"></span>
                        </div>
                        <div class="form-group form-group-icon-left">
                            <textarea id="description" class="form-control form-control-2" placeholder="Description"></textarea>
                            <span class="spanError form-control-2"></span>
                        </div>
                        <div class="form-group form-group-icon-left">
                            <input class="btn btn-primary mt10-1" id="contact_pick" value="Send" type="submit">

                            <div id="divMessage" class="alert alert-block fade in"></div>
                        </div>
                    </form>
                  </aside>
              </div>
          </div>
  		</div>
  	</div>
  </div>
<script type="text/javascript">
  $("#contact_pick").click(function(event) {
    event.preventDefault();
    name = $("#name").val();
    phoneNo = $("#phoneNo").val();
    institute = $("#institute").val();
    name = $("#name").val();

  });
</script>
<script type="text/javascript">
  $("#contact_pick").click(function(event) {
    event.preventDefault();
    name = $("#name").val();
    phoneNo = $("#phoneNo").val();
    institute = $("#institute").val();
    vehicle_type = $("#vehicle_type").val();
    description = $("#description").val();


    if (name.length < 2) {
      notify('Information','Please enter a valid name');
      return 0;
    }
    if (phoneNo.length < 2) {
      notify('Information','Please enter a valid phone number');
      return 0;
    }
    if (institute.length < 2) {
      notify('Information','Please enter a institute name');
      return 0;
    }
    if (vehicle_type === 'no' || vehicle_type == null) {
      notify('Information','Please Choice vehicle type');
      return 0;
    }
    if (description.length < 3) {
      notify('Information','Please enter a description');
      return 0;
    }

    $.ajax({
      url: '{{route('pickAndDrop.store')}}',
      type: 'POST',
      data: {
        name: name,
        phoneNo: phoneNo,
        institute: institute,
        vehicle_type: vehicle_type,
        description: description,
        _token: "{{ csrf_token() }}"
      }
    })
    .done(function(Response) {
      result = $.parseJSON(Response)

      if (result.status == 0) {
        notify('error',result.message);
      }
      if (result.status == 1) {
        notify('succuess',result.message);
      }
    })
    .fail(function() {
      notify('error','there was issue when completing your request please try again');
    });

  });
</script>

@endsection

resources/views/service/pickAndDrop.blade.php
@extends('layouts.app')
@section('title')
  Bsahab - Pick and Drop
@endsection
@section('body')

  <div class="full-r"><img src="img/trancport-facility-header.jpg"  alt="Rental Car Services - Pick and Drop Services - Bhai Sahab transport" title="Rental Car Services - Pick and Drop Services - Bhai Sahab transport"/></div>
  <div class="container" itemscope itemtype="http://schema.org/ProfessionalService">
  	<div class="row" itemprop="description">
  		<div class="col-md-12">
              <div class="col-sm-8 col-md-8 col-lg-9" style="text-align: justify;line-height:27px;padding: 0px 20px 15px;font-size:17px;font-family:'Roboto', arial, helvetica, sans-serif;">
                  <h1 style="margin-top:20px;">Pick and Drop Service in Lahore</h1>

          <p>At times, when you are travelling by yourself and travelling convenience becomes a bit tricky due to so many reasons such as not having a car, which is the most common and reasonable one along with not knowing anyone in the locality that can help you and drop you off at the place you want to be. However, such reasons shouldn’t deter you from trying alternates, maybe you don’t want to disturb your family or need to be somewhere immediate without relying on someone’s help: that’s where Bhai Sahab’s pick and drop service comes in.</p><br />
          <p>While we offer various other travel services such as rentals and tours, we also have branched out to pick and drop services as well, while our pick and drop service is mainly available for Lahore and surrounding areas, that doesn’t mean we compromise on our services, we actually focus on serving our customers to the best of our ability all the while showing you how we strive to be the number one transport service in our motherland.</p>
          <p><b>How Pick and Drop works.</b></p>
          <p>Our service is very simple and easy to comprehend and use, what you do is contact us to arrange a pick and drop service or you can go to the service section on our site, visit our Pick and drop page and leave your name, contact number, the college you are current enrolled in and the type of vehicle you would like to be picked up on along with a description section for any other special needs alongside your request,  our service strives to achieve the best quality it potentially can alongside being very competitive in prices to facilitate students who can’t earn yet or to keep it as cheap as possible as we all know transport can be  quite expensive.</p>
          <p>What differentiates Bhai Sahabs versatile services from the rest is that we provide all types of services under one proof, our pick and drop services in only one of the many equipment in our arsenal, our dedicated teams, our high quality vehicles and our prompt services. Rather than going of the more expensive options for the same comfort, Bhai Sahab will get you to point B from point A in the most convenient and cheaper manner.</p>
              </div>

              <div class="col-sm-4 col-md-4 col-lg-3" style="margin-bottom:100px">
              <div class="row">
                  <h5 class="" style="margin-top: 20px; border-bottom: 2px solid rgb(237, 131, 35); padding-bottom: 5px;">Contact Us for pick and drop service with in Lahore.</h5>
                  <aside class="sidebar-left">
                      <form id="service-contact">
                          <div class="form-group form-group-icon-left">
                              <input maxlength="150" class="form-control form-control-2" value="" id="name" placeholder="Name" type="text">
                              <span class="spanError form-control-2" id="spanContactName"></span>
                          </div>
                          <div class="form-group form-group-icon-left">
                              <input class="form-control form-control-2" id="phoneNo" placeholder="Phone No" type="text">
                              <span class="spanError form-control-2" id="spanContactPhone"></span>
                          </div>
                          <div class="form-group form-group-icon-left">
                              <input class="form-control form-control-2" id="institute" placeholder="College / University" type="text">
                              <span class="spanError form-control-2" id="spanContactLocation"></span>
                          </div>
                          <div class="form-group form-group-icon-left">
                              <select id="vehicle_type" class="form-control form-control-2">
                                  <option disabled selected value="no">Vehicle Type</option>
                                  <option value="Rickshaw">Rickshaw</option>
                                  <option value="Other">Others</option>
                              </select>
                              <span class="spanError form-control-2" id="spanVehicleType"></span>
                          </div>
                          <div class="form-group form-group-icon-left">
                              <textarea id="description" class="form-control form-control-2" placeholder="Description"></textarea>
                              <span class="spanError form-control-2"></span>
                          </div>
                          <div class="form-group form-group-icon-left">
                              <input class="btn btn-primary mt10-1" id="contact_pick" value="Send" type="submit">

                              <div id="divMessage" class="alert alert-block fade in"></div>
                          </div>
                      </form>
                  </aside>
              </div>
          </div>
  		</div>
  	</div>
  </div>
<script type="text/javascript">
  $("#contact_pick").click(function(event) {
    event.preventDefault();
    name = $("#name").val();
    phoneNo = $("#phoneNo").val();
    institute = $("#institute").val();
    vehicle_type = $("#vehicle_type").val();
    description = $("#description").val();


    if (name.length < 2) {
      notify('Information','Please enter a valid name');
      return 0;
    }
    if (phoneNo.length < 2) {
      notify('Information','Please enter a valid phone number');
      return 0;
    }
    if (institute.length < 2) {
      notify('Information','Please enter a institute name');
      return 0;
    }
    if (vehicle_type === 'no' || vehicle_type == null) {
      notify('Information','Please Choice vehicle type');
      return 0;
    }
    if (description.length < 3) {
      notify('Information','Please enter a description');
      return 0;
    }

    $.ajax({
      url: '{{route('pickAndDrop.store')}}',
      type: 'POST',
      data: {
        name: name,
        phoneNo: phoneNo,
        institute: institute,
        vehicle_type: vehicle_type,
        description: description,
        _token: "{{ csrf_token() }}"
      }
    })
    .done(function(Response) {
      result = $.parseJSON(Response)

      if (result.status == 0) {
        notify('error',result.message);
      }
      if (result.status == 1) {
        notify('succuess',result.message);
      }
    })
    .fail(function() {
      notify('error','there was issue when completing your request please try again');
    });

  });
</script>
@endsection

resources/views/service/rentACar.blade.php
@extends('layouts.app')
@section('title')
  Bsahab - Rent a Car
@endsection
@section('body')

  <div class="full-r"><img src="img/service-banner.jpg"  alt="Rental Car Services - Pick and Drop Services - Bhai Sahab transport" title="Rental Car Services - Pick and Drop Services - Bhai Sahab transport"/></div>
  <div class="container" itemscope itemtype="http://schema.org/ProfessionalService">
  	<div class="row" itemprop="description">
  		<div class="col-md-12">
              <div class="col-sm-8 col-md-8 col-lg-9" style="text-align: justify;line-height:27px;padding: 0px 20px 15px;font-size:17px;font-family:'Roboto', arial, helvetica, sans-serif;">
                  <h1 style="margin-top:20px;">Rent a Car in Lahore Johar Town, Defence and DHA</h1>
                  <p>Bhai sahib transport is a rent-a-car service that aims to fulfill your travel needs. We offer diverse packages of all types of cars for your travel convenience such as cars for your family outings or if you require more spacious seating arrangement, then we have you covered with our line-up of vans and buses for those long trips with those important ones. We will provide you with all the necessary vehicles for your need and more, by providing accurate in-depth information as to what the rental car services entails.
Amongst the other Rent a car in Lahore, we rank fairly high. If you look at our website, we have vehicle capacity ranging from 5 passengers to 42 passengers, ready for any scenario that you want to undertake for as many people as we can accommodate. For each car, we have included a demo picture along with the necessary info such as:
</p>

<ul>
  <li>The amount of passengers it can accommodate </li>
  <li>The number of doors on the vehicle </li>
  <li>Baggage capacity </li>
  <li>Weather the car is automatic or manual (for the renter’s preference) </li>
  <li>The type of liquid the car consumes (Petrol/Diesel etc.) </li>
  <li>Air conditioned or not. </li>
  <li>Other miscellaneous such as climate control, power locks, multimedia screen etc.</li>

</ul>

                  <p>Alongside stating the features of the potential car that you may want to rent, we have also included prices, these prices shows the rental fee for the car for the day. This would easily portray the price for to be compared to your budget so that you can get the most of the deal, by striking a balance between cost and comfort. While our prices are low which would go to show that we run a cheap Rent a car in Lahore but the less prices are due to being competitive. </p>

                  <p>Lastly, why should you choose us. Bhai Sahab is one of the best rental companies around town, with such a deep inventory when it comes to offering a wide selection of events, a well-detailed website for your convenience where every single detail is explained aesthetically.
                  <p>Our Motto ‘Explore Pakistan with comfort’ is something that we take pride in as our products are well-maintained so that the same rental car would be in its best shape when serving a later customer as we believe in that comfort and quality go hand in hand in the rental business, how we treat our vehicles goes to show how much we care.


              </div>


  		</div>
  	</div>
  </div>
<script type="text/javascript">
  $("#contact_pick").click(function(event) {
    event.preventDefault();
    name = $("#name").val();
    phoneNo = $("#phoneNo").val();
    institute = $("#institute").val();
    name = $("#name").val();

  });
</script>
@endsection

resources/views/service/tourManagement.blade.php
@extends('layouts.app')
@section('title')
  Bsahab - Tour Management
@endsection
@section('body')

  <div class="full-r"><img src="img/tour-management-111.jpg"  alt="Rental Car Services - Pick and Drop Services - Bhai Sahab transport" title="Rental Car Services - Pick and Drop Services - Bhai Sahab transport"/></div>
  <div class="container" itemscope itemtype="http://schema.org/ProfessionalService">
  	<div class="row" itemprop="description">
  		<div class="col-md-12">
              <div class="col-sm-8 col-md-8 col-lg-9" style="text-align: justify;line-height:27px;padding: 0px 20px 15px;font-size:17px;font-family:'Roboto', arial, helvetica, sans-serif;">
                  <h1 style="margin-top:20px;">Services</h1>

  		<h2>Tour Management</h2>
          <p>	One of the main attractions in Pakistan that you’ll come to see and even at times, experience are the tours of the different direction that this country has to offer, whether it be to the Sindh side in the south to traverse some deserts and look at the Cholistan fort or be it at the north to take in the beauty of the Himalayan range alongside the amazing Kashmir with a side of hills and the greenery that compliments it. Whatever the nature of your tour be, Bhai Sahab has you covered with their vast array of rental car available for your convenience. </p><br />
 <p>	Not only will we provide you with the tools necessary for travel such as Rent a Car but we will also arrange the whole trip for you in a neatly compiled, descriptive package with each detail laid out in an itinerary form for you decide which tour would suit your desires. </p><br />
 <p>	Our wide array of cars can quip with any sort of tour you so desire, be it a joint family trip to the northern side or a close group of friends in an SUV exploring the hilly areas of Pakistan. We have our 48 seaters to 4 seaters, you can be planning will be so much more flexible when you consider Bhai Sahab. </p><br />
 <p>	One of the best things about Bhai Sahab is that our organization is the amalgamation of everything you want for traveling, not only do we provide with rental cars but we also plan tours and trips for you, you can plan a whole outing from scratch by just being present, not many organizations provide the array of services that we do, all under one roof. </p><br />
 <p>Our motto “Explore Pakistan with comfort” displays that we take our tours seriously, those long winding roads and travels that can go on for days and nights can be quite tiresome, which is why we strive to make your journey as comfortable as possible by maintaining our vehicles so that they are capable of helping you reach your destination all the while, making that trip as comfortable as possible for you, your family and your business partner. </p><br />
              </div>


  		</div>
  	</div>
  </div>
<script type="text/javascript">
  $("#contact_pick").click(function(event) {
    event.preventDefault();
    name = $("#name").val();
    phoneNo = $("#phoneNo").val();
    institute = $("#institute").val();
    name = $("#name").val();

  });
</script>
@endsection