routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

  Route::prefix('admin')->group(function () {

    Route::get('testing','adminController@test');
    Route::get('/seo','adminController@seoIndex')->name('seoIndex');
    Route::get('/seoCreate','adminController@seoCreate')->name('seoCreate');
    Route::post('/seoStore','adminController@seoStore')->name('seoStore');
    Route::get('/seoEdit/{id}','adminController@seoEdit')->name('seoEdit');
    Route::post('/seoPut','adminController@seoPut')->name('seoPut');
    Route::get('/seoCollection','adminController@seoCollection')->name('seoCollection');
    Route::get('/','adminController@home')->name('adminHome');
    Route::post('/checkStatus','adminController@checkStatus')->name('checkStatus');
    Route::get('/subscriberData','adminController@subscriberData')->name('subscriberData');
    Route::get('/subscribLetterList','adminController@subscribLetterList')->name('subscribLetterList');
    Route::get('/userMessages','adminController@userMessages')->name('userMessages');
    Route::get('/getUserMessageJson','adminController@getUserMessageJson')->name('getUserMessageJson');
    Route::post('/setUserMessageSeen','adminController@setUserMessageSeen')->name('setUserMessageSeen');
    Route::post('/deleteUserMessage','adminController@deleteUserMessage')->name('deleteUserMessage');
    Route::post('/deleteDestination','adminController@deleteDestination')->name('deleteDestination');
    Route::get('/destination','adminController@destination')->name('adminDestination');
    Route::get('/createDestination','adminController@createDestination')->name('createDestination');
    Route::post('/addDestination','adminController@addDestination')->name('addDestination');
    Route::get('/editDestination/{id}','adminController@editDestination')->name('editDestination');
    Route::post('/updateDestination/{id}','adminController@updateDestination')->name('updateDestination');
    Route::get('/vehicles','adminController@vehicles')->name('adminVehicles');
    Route::get('/createVehicle','adminController@createVehicle')->name('createVehicle');
    Route::post('/addVehicle','adminController@addVehicle')->name('addVehicle');
    Route::get('/editVehicle/{id}','adminController@editVehicle')->name('editVehicle');
    Route::post('/updateVehicle/{id}','adminController@updateVehicle')->name('updateVehicle');
    Route::post('/deleteVehicle','adminController@deleteVehicle')->name('deleteVehicle');
    Route::post('/deleteSubsriber','adminController@deleteSubsriber')->name('deleteSubsriber');
    Route::post('/deleteGalleryImage','adminController@deleteGalleryImage')->name('deleteGalleryImage');
    Route::get('/vehicleBooking','adminController@vehicleBooking')->name('vehicleBooking');
    Route::post('/getVehicleBooking','adminController@getVehicleBooking')->name('getVehicleBooking');
    Route::post('/deleteBooking','adminController@deleteBooking')->name('deleteBooking');
    Route::post('setBookingSeen','adminController@setBookingSeen')->name('setBookingSeen');
    Route::get('/pickDrop','adminController@pickDrop')->name('pickDropAdmin');
    Route::post('/getPickDrop','adminController@getPickDrop')->name('getPickDrop');
    Route::post('/deletePickAndDrop','adminController@deletePickAndDrop')->name('deletePickAndDrop');
    Route::post('/setPickAndDrop','adminController@setPickAndDrop')->name('setPickAndDrop');
    Route::post('/getInitilizationData','adminController@getInitilizationData')->name('getInitilizationData');
    Route::post('/deleteDestinationGalleryImage','adminController@deleteDestinationGalleryImage')->name('deleteDestinationGalleryImage');
});

Auth::routes();

Route::post('getVehcilesJson','VehicleController@getVehcilesJson')->name('getVehcilesJson');
Route::resource('pickAndDrop','PickAndDropController');
Route::get('/', 'HomeController@index')->name('ahome');
Route::get('/', 'HomeController@index')->name('home');
Route::get('/home',function(){
  return Redirect::to('/');
});
Route::post('/subscribNewLetter','NewsLetterController@store')->name('subscribNewLetter');
Route::post('/userMessageSave','UserMessageController@store')->name('userMessageSave');
Route::get('vehicle/{id}/{name?}','VehicleController@vehicle');
Route::resource('/rental-vehicles','VehicleController');
Route::resource('/services','ServiceController');
Route::get('/rent-a-car','ServiceController@rentACar')->name('rent-a-Car');
Route::get('/tour-management','ServiceController@tourManagement')->name('tour-management');
Route::get('/pick-and-drop','ServiceController@pickAndDrop')->name('pick-and-drop');
Route::get('/policy',function(){
  return view('policy');
})->name('policy');
Route::get('/tourist-attraction','DestinationController@provinces')->name('provinces');
Route::post('/car-Booking',"carBookingController@store")->name('car-Booking');
Route::get('/tourist-attraction-Detail/{id}/{title?}','DestinationController@destination')->name('destination');
Route::get('/tourist-attraction/{id}/{title?}','DestinationController@provinceNew')->name('provinceNew');
Route::resource('/destinations','DestinationController');
Route::post('planTour','TourController@planeTour')->name('planeTour');
Route::resource('/plan-my-tour','TourController');
Route::get('contact-us','UserMessageController@index')->name('contact-us');
Route::get('/loyalty-card',function(){
  return view('loyalty-card');
})->name('loyalty-card');

app/destination.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class destination extends Model
{
  protected $primaryKey = 'destination_id';
  public $timestamps = false;
}

app/Http/Controllers/DestinationController.php
<?php

namespace App\Http\Controllers;

use App\destination;
use Illuminate\Http\Request;
use App\destinationGallery as destinationGallery;

class DestinationController extends Controller
{
    public function provinces(){
      $destinations = destination::all();
      $filterdDestations = destination::where('parent','=',0)->get();
      return view('destination.provinces',compact('destinations','filterdDestations'));
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id = null)
    {
        $destinations = destination::where('province','=',$id)->get();
        return view('destination.index',compact('destinations'));
    }
    public function destination($id,$title = null)
    {
        if ($title != null) {
          $destination = destination::where('destination_id','=',$id)->first();
          $destination->videoThumbnail = null;
          $destinationGallery = destinationGallery::where('destinationId','=',$id)->get();
          if ($destination->videoLink != null) {
            $url = $destination->videoLink;
            parse_str( parse_url( $url, PHP_URL_QUERY ), $my_array_of_vars );
            $destination->videoThumbnail = "https://img.youtube.com/vi/".$my_array_of_vars['v']."/0.jpg";
          }

          return view('destination.show',compact('destination','destinationGallery'));
        }
        $destinations = destination::where('province','=',$id)->get();
        return view('destination.index',compact('destinations'));
    }
    public function provinceNew($id,$title = null){
      $destinations = destination::where('province','=',$id)->get();

      return view('destination.index',compact('destinations'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\destination  $destination
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $destination = destination::where('destination_id','=',$id)->first();
      // dd($destination);
      return view('destination.show',compact('destination'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\destination  $destination
     * @return \Illuminate\Http\Response
     */
    public function edit(destination $destination)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\destination  $destination
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, destination $destination)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\destination  $destination
     * @return \Illuminate\Http\Response
     */
    public function destroy(destination $destination)
    {
        //
    }
}

resources/views/destination/index.blade.php
@extends('layouts.app')
@section('title','Rent a Car | Economy Car Rental Deals | Car for Rent')
@section('body')
<style type="text/css">
     #map {
        height: 350px;
		margin-bottom:50px;
      }
	  .iw-content img
	  {
		  width:70px !important;
	  }

#map img {
	max-width: none !important;
}
.gm-style-iw {


	left:21px !important;

}

#iw-container .iw-title {
	font-family: 'Open Sans Condensed', sans-serif;
	font-size: 22px;
	font-weight: 400;
	padding: 10px;
	background-color: #48b5e9;
	color: white;
	margin: 0;
	border-radius: 2px 2px 0 0;
}

.iw-content img {
	float: right;
	margin: 0 5px 5px 10px;
}
.iw-subTitle {
	font-size: 16px;
	font-weight: 700;
	padding: 5px 0;
}
.iw-bottom-gradient {
	position: absolute;
	width: 326px;
	height: 25px;
	bottom: 10px;
	right: 18px;
	background: linear-gradient(to bottom, rgba(255,255,255,0) 0%, rgba(255,255,255,1) 100%);
	background: -webkit-linear-gradient(top, rgba(255,255,255,0) 0%, rgba(255,255,255,1) 100%);
	background: -moz-linear-gradient(top, rgba(255,255,255,0) 0%, rgba(255,255,255,1) 100%);
	background: -ms-linear-gradient(top, rgba(255,255,255,0) 0%, rgba(255,255,255,1) 100%);
}

.detinationImage {
  z-index: 1;
}
.overlay {
    position: absolute;
    top: 0;
    height: 173px;
    width: 90%;
  	z-index: 3;
    opacity: 0.5;
}
</style>

<div id="map"></div>

<div class="container">

</div>

<script type="text/javascript">
$(document).ready(function() {

var map;
  var latlng = new google.maps.LatLng(30.0706, 71.0937);
  var myOptions = {
  zoom: 5,
  center: latlng,
  draggable: false,
  mapTypeId: google.maps.MapTypeId.ROADMAP,
};
map = new google.maps.Map(document.getElementById("map"), myOptions);
@foreach ($destinations as $destination)
var marker = new google.maps.Marker
(
    {
        position: new google.maps.LatLng({{$destination->latitude}},{{$destination->longitude}}),
        map: map,
        title: '{{$destination->title}}',
        icon: 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png'
    }
);

var content = '<div id="iw-container">' +
'<div class="iw-title">{{$destination->title}}</div>'+
'<div style="float:left; width:50%;"><div class="iw-content">'+
'<div class="iw-subTitle">History</div>'+
'<p>{{preg_replace('/[\r\n]+/','', $destination->description)}}</p>'+
'<br><a href = "{{URL::to('/') .'/tourist-attraction-Detail/'.$destination->destination_id."/".preg_replace('/\s+/', '-',$destination->title)}}">Click Here </a> For more details</p>'+
'</div>' +
'</div>'+
'<div style="float:right; width:47%;">'+
'<img src="@if(file_exists('img/thumbnail/'.$destination->image)){{asset('img/thumbnail/'.$destination->image)}}@else{{asset('img/'.$destination->image)}}@endif" height="150px" width="150px">' +
'</div>'+
'</div>';

var infowindow = new google.maps.InfoWindow();
google.maps.event.addListener(marker,'click', (function(marker,content,infowindow){
return function() {
  infowindow.setContent(content);
  infowindow.open(map,marker);
};
})(marker,content,infowindow));
@endforeach
});

</script>
<div class="container">

<div class="row row-wrap">

  @foreach ($destinations as $destination)
<div class="col-md-3" >
  <a href="{{URL::to('/') .'/tourist-attraction-Detail/'.$destination->destination_id."/".preg_replace('/\s+/', '-',$destination->title)}}">
  <p style="position: absolute;top: 40%;font-size: 30px;color: #fff;text-align: center;margin: 0 auto;width: 90%;z-index:111;">{{$destination->title}}</p></a>
  <div class="thumb">
      <header class="thumb-header">
          <a class="" href="{{URL::to('/') .'/tourist-attraction-Detail/'.$destination->destination_id."/".preg_replace('/\s+/', '-',$destination->title)}}" itemprop="mainEntityOfPage">
              @if (file_exists('img/thumbnail/'.$destination->image))
                <img src="{{asset('img/thumbnail/'.$destination->image)}}" class="detinationImage" alt="{{$destination->title}}" title="{{$destination->title}}" itemprop="image" height="173">
              @else
                <img src="{{asset('img/'.$destination->image)}}" class="detinationImage" alt="{{$destination->title}}" title="{{$destination->title}}" itemprop="image" height="173">
              @endif
              <img class="overlay" src="{{asset('img/overlay.png')}}">
          </a>
      </header>
  </div>
</div>
@endforeach

	</div>
</div>


@endsection

resources/views/destination/provinces.blade.php
@extends('layouts.app')
@section('title','Rent a Car | Economy Car Rental Deals | Car for Rent')
@section('body')
<style type="text/css">
     #map {
        height: 350px;
		margin-bottom:50px;
      }
	  .iw-content img
	  {
		  width:70px !important;
	  }

#map img {
	max-width: none !important;
}
.gm-style-iw {


	left:21px !important;

}

#iw-container .iw-title {
	font-family: 'Open Sans Condensed', sans-serif;
	font-size: 22px;
	font-weight: 400;
	padding: 10px;
	background-color: #48b5e9;
	color: white;
	margin: 0;
	border-radius: 2px 2px 0 0;
}

.iw-content img {
	float: right;
	margin: 0 5px 5px 10px;
}
.iw-subTitle {
	font-size: 16px;
	font-weight: 700;
	padding: 5px 0;
}
.iw-bottom-gradient {
	position: absolute;
	width: 326px;
	height: 25px;
	bottom: 10px;
	right: 18px;
	background: linear-gradient(to bottom, rgba(255,255,255,0) 0%, rgba(255,255,255,1) 100%);
	background: -webkit-linear-gradient(top, rgba(255,255,255,0) 0%, rgba(255,255,255,1) 100%);
	background: -moz-linear-gradient(top, rgba(255,255,255,0) 0%, rgba(255,255,255,1) 100%);
	background: -ms-linear-gradient(top, rgba(255,255,255,0) 0%, rgba(255,255,255,1) 100%);
}

.detinationImage {
  z-index: 1;
}
.overlay {
    position: absolute;
    top: 0;
    height: 173px;
    width: 90%;
  	z-index: 3;
    opacity: 0.5;
    left: 15px;
}
</style>

<div id="map"></div>

<div class="container">

</div>

<script type="text/javascript">
var map;
  var latlng = new google.maps.LatLng(30.0706, 71.0937);
  var myOptions = {
  zoom: 5,
  center: latlng,
  draggable: false,
  mapTypeId: google.maps.MapTypeId.ROADMAP,
};
map = new google.maps.Map(document.getElementById("map"), myOptions);
@foreach ($destinations as $destination)
var marker = new google.maps.Marker
(
    {
        position: new google.maps.LatLng({{$destination->latitude}},{{$destination->longitude}}),
        map: map,
        title: '{{$destination->title}}',
        icon: 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png'
    }
);

var content = '<div id="iw-container">' +
'<div class="iw-title">{{$destination->title}}</div>'+
'<div style="float:left; width:50%;"><div class="iw-content">'+
'<div class="iw-subTitle">History</div>'+
'<p>{{preg_replace('/[\r\n]+/','', $destination->description)}}</p>'+
'<br><a href = "{{route('destinations.show',$destination->id)}}">Click Here </a> For more details</p>'+
'</div>' +
'</div>'+
'<div style="float:right; width:47%;">'+
'<img src="{{asset('img/'.$destination->image)}}" alt="$title" height="150px" width="150px">' +
'</div>'+
'</div>';

var infowindow = new google.maps.InfoWindow();
google.maps.event.addListener(marker,'click', (function(marker,content,infowindow){
return function() {
  infowindow.setContent(content);
  infowindow.open(map,marker);
};
})(marker,content,infowindow));
@endforeach

</script>
<div class="container">

<div class="row row-wrap">



<div class="col-md-3" >
<a href="{{route('provinceNew',1)}}/punjab"><p style="position: absolute;top: 40%;font-size: 30px;color: #fff;text-align: center;margin: 0 auto;width: 90%;z-index:111;">Punjab</p></a>
  <div class="thumb">
      <header class="thumb-header">
          <a class="" href="{{route('provinceNew',1)}}/punjab" itemprop="mainEntityOfPage">
              <img src="{{asset('img/thumbnail/punjab.png')}}" class="detinationImage" alt="punjab" title="punjab" itemprop="image" height="173">
              <img class="overlay" src="{{asset('img/overlay.png')}}">
          </a>
      </header>
  </div>
</div>
<div class="col-md-3" >
<a href="{{route('provinceNew',2)}}/sindh"><p style="position: absolute;top: 40%;font-size: 30px;color: #fff;text-align: center;margin: 0 auto;width: 90%;z-index:111;">Sindh</p></a>
  <div class="thumb">
      <header class="thumb-header">
          <a class="" href="{{route('provinceNew',2)}}/sindh" itemprop="mainEntityOfPage">
              <img src="{{asset('img/thumbnail/sindh.jpg')}}" class="detinationImage" alt="Sindh" title="Sindh" itemprop="image" height="173">
              <img class="overlay" src="{{asset('img/overlay.png')}}">
          </a>
      </header>
  </div>
</div>
<div class="col-md-3" >
<a href="{{route('provinceNew',3)}}/Khyber-Pakhtunkhwa"><p style="position: absolute;top: 40%;font-size: 30px;color: #fff;text-align: center;margin: 0 auto;width: 90%;z-index:111;">Khyber Pakhtunkhwa</p></a>
  <div class="thumb">
      <header class="thumb-header">
          <a class="" href="{{route('provinceNew',3)}}/Khyber-Pakhtunkhwa" itemprop="mainEntityOfPage">
              <img src="{{asset('img/thumbnail/kpk.jpg')}}" class="detinationImage" alt="Khyber Pakhtunkhwa" title="Khyber Pakhtunkhwa" itemprop="image" height="173">
              <img class="overlay" src="{{asset('img/overlay.png')}}">
          </a>
      </header>
  </div>
</div>
<div class="col-md-3" >
<a href="{{route('provinceNew',4)}}/blochistan"><p style="position: absolute;top: 40%;font-size: 30px;color: #fff;text-align: center;margin: 0 auto;width: 90%;z-index:111;">Blochistan</p></a>
  <div class="thumb">
      <header class="thumb-header">
          <a class="" href="{{route('provinceNew',4)}}/blochistan" itemprop="mainEntityOfPage">
              <img src="{{asset('img/thumbnail/blochistan.jpg')}}" class="detinationImage" alt="blochistan" title="blochistan" itemprop="image" height="173">
              <img class="overlay" src="{{asset('img/overlay.png')}}">
          </a>
      </header>
  </div>
</div>
<div class="col-md-3" >
<a href="{{route('provinceNew',5)}}/Gilgit-Baltistan"><p style="position: absolute;top: 40%;font-size: 30px;color: #fff;text-align: center;margin: 0 auto;width: 90%;z-index:111;">Gilgit-Baltistan</p></a>
  <div class="thumb">
      <header class="thumb-header">
          <a class="" href="{{route('provinceNew',5)}}/Gilgit-Baltistan" itemprop="mainEntityOfPage">
              <img src="{{asset('img/thumbnail/baltistan.jpg')}}" class="detinationImage" alt="Gilgit-Baltistan" title="Gilgit-Baltistan" itemprop="image" height="173">
              <img class="overlay" src="{{asset('img/overlay.png')}}">
          </a>
      </header>
  </div>
</div>
<div class="col-md-3" >
<a href="{{route('provinceNew',6)}}/Azad-kashmir"><p style="position: absolute;top: 40%;font-size: 30px;color: #fff;text-align: center;margin: 0 auto;width: 90%;z-index:111;">Azad kashmir</p></a>
  <div class="thumb">
      <header class="thumb-header">
          <a class="" href="{{route('provinceNew',6)}}/Azad-kashmir" itemprop="mainEntityOfPage">
              <img src="{{asset('img/thumbnail/kashmir.jpg')}}" class="detinationImage" alt="Azad kashmir" title="Azad kashmir" itemprop="image" height="173">
              <img class="overlay" src="{{asset('img/overlay.png')}}">
          </a>
      </header>
  </div>
</div>







	</div>
</div>


@endsection

resources/views/destination/show.blade.php
@extends('layouts.app')
@section('title','Rent a Car | Economy Car Rental Deals | Car for Rent')
@section('body')
  <link href="//cdn.quilljs.com/1.3.6/quill.core.css" rel="stylesheet">

<style type="text/css">
     #map {
        height: 350px;
		margin-bottom:50px;
      }
	  .iw-content img
	  {
		  width:70px !important;
	  }

#map img {
	max-width: none !important;
}
.gm-style-iw {


	left:21px !important;

}

#iw-container .iw-title {
	font-family: 'Open Sans Condensed', sans-serif;
	font-size: 22px;
	font-weight: 400;
	padding: 10px;
	background-color: #48b5e9;
	color: white;
	margin: 0;
	border-radius: 2px 2px 0 0;
}

.iw-content img {
	float: right;
	margin: 0 5px 5px 10px;
}
.iw-subTitle {
	font-size: 16px;
	font-weight: 700;
	padding: 5px 0;
}
.iw-bottom-gradient {
	position: absolute;
	width: 326px;
	height: 25px;
	bottom: 10px;
	right: 18px;
	background: linear-gradient(to bottom, rgba(255,255,255,0) 0%, rgba(255,255,255,1) 100%);
	background: -webkit-linear-gradient(top, rgba(255,255,255,0) 0%, rgba(255,255,255,1) 100%);
	background: -moz-linear-gradient(top, rgba(255,255,255,0) 0%, rgba(255,255,255,1) 100%);
	background: -ms-linear-gradient(top, rgba(255,255,255,0) 0%, rgba(255,255,255,1) 100%);
}

.detinationImage {
  z-index: 1;
}
.overlay {
    position: absolute;
    top: 0;
    height: 173px;
    width: 90%;
  	z-index: 3;
    opacity: 0.5;
}
</style>
<style media="screen">
.fotorama__stage__frame.fotorama__active {
  z-index: 8;
}
.fotorama__video-play{
  /*position:relative;*/
  z-index:100000;
  /*left:-50px;
  top:10px;*/
  background:url('/img/youtube.png');
  background-size: contain;
  /*width: 20px;
  height: 20px;
  display:block;*/
}
</style>
<div id="map"></div>

<div class="container">

</div>

<script type="text/javascript">
$(document).ready(function() {
var map;
  var latlng = new google.maps.LatLng(30.0706, 71.0937);
  var myOptions = {
  zoom: 5,
  center: latlng,
  draggable: false,
  mapTypeId: google.maps.MapTypeId.ROADMAP,
};
map = new google.maps.Map(document.getElementById("map"), myOptions);

var marker = new google.maps.Marker
(
    {
        position: new google.maps.LatLng({{$destination->latitude}},{{$destination->longitude}}),
        map: map,
        title: '{{$destination->title}}',
        icon: 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png'
    }
);


});

</script>
<div class="container">





<div class="row">
<div class="col-md-6" style="    margin-bottom: 59px;">
	<h1>{{$destination->title}}</h1>
  <a href="mailto:bhaisahabtrans@gmail.com"><i class="fa fa-envelope"></i> E-mail Car Agent</a>
  <span style="padding-left: 10px;"><i class="fa fa-phone"></i>+92-320-440-0993‬ </span>
<br>
<div class="fotorama" data-width="700" data-ratio="700/467" data-max-width="100%" data-allowfullscreen="true"  data-loop="true"   data-nav="thumbs">
    @if($destination->videoThumbnail != null)
      <a href='{{ preg_replace("/^http:/i", "https:", $destination->videoLink)}}'   data-video="true">Rose</a>

    @endif
    <a href='{{asset("img/$destination->image")}}'><img src='{{asset("img/$destination->image")}}' width='494'     height='370'></a>
    @foreach ($destinationGallery as $obj2)
      <a href='{{asset("img/$destination->destination_id/$obj2->image")}}'><img src='{{asset("img/$destination->destination_id/$obj2->image")}}' width='494'     height='370'></a>
    @endforeach
</div>


</div>

<div class="col-md-6" style="margin-top:150px;">
  <div class="pull-right">
		    <p>
          @if (Request::ip() == "115.186.32.40")



          {!! $destination->description !!}

          @else
            {!! $destination->description !!}
          @endif
        	</p>
  </div>
</div>

</div>

	<div class="row row-wrap">
	</div>

</div>


</div>


@endsection